/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto2.view;

import com.mycompany.proyecto2.controller.UsuarioControler;
import com.mycompany.proyecto2.main.abstracto.Usuario;

import com.mycompany.proyecto2.model.instructor;
import javax.swing.JOptionPane;

/**
 *
 * @author erick
 */
public class VistaGestionInstructores extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaGestionInstructores.class.getName());

    /**
     * Creates new form VistaGestionInstructores
     */
    public VistaGestionInstructores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCrearInstructor = new javax.swing.JButton();
        btnBuscarInstructor = new javax.swing.JButton();
        btnEditarInstructor = new javax.swing.JButton();
        btnEliminarInstructor = new javax.swing.JButton();
        btnCargarCSV = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Gestionar Instructores");

        btnCrearInstructor.setText("Crear Instructor");
        btnCrearInstructor.addActionListener(this::btnCrearInstructorActionPerformed);

        btnBuscarInstructor.setText("Buscar Instructor");
        btnBuscarInstructor.addActionListener(this::btnBuscarInstructorActionPerformed);

        btnEditarInstructor.setText("Editar Instructor");
        btnEditarInstructor.addActionListener(this::btnEditarInstructorActionPerformed);

        btnEliminarInstructor.setText("Eliminar Instructor");
        btnEliminarInstructor.addActionListener(this::btnEliminarInstructorActionPerformed);

        btnCargarCSV.setText("Cargar CSV");

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnCrearInstructor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscarInstructor, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(btnEditarInstructor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEliminarInstructor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCargarCSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearInstructor)
                    .addComponent(btnEliminarInstructor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarInstructor)
                    .addComponent(btnCargarCSV))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarInstructor)
                    .addComponent(btnRegresar))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearInstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearInstructorActionPerformed
     VistaRegistrarse vRegistrarse = new VistaRegistrarse();
     vRegistrarse.setVisible(true);
    }//GEN-LAST:event_btnCrearInstructorActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnEditarInstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarInstructorActionPerformed
     UsuarioControler u = new UsuarioControler();
     String codigo = JOptionPane.showInputDialog("Ingrese código del instructor");
     if(codigo == null) return;
     Usuario usuario = u.buscarPorCodigo(codigo); 
     if(usuario == null){
      JOptionPane.showMessageDialog(null, "Instructor  no encontrado");
     return;
  }


    if(!(usuario instanceof instructor)){
    JOptionPane.showMessageDialog(null, "El código no pertenece a un Instructor");
    return;
    }
    instructor i = (instructor) usuario;
    String nuevoNombre = JOptionPane.showInputDialog("Ingrese el nombre", i.getNombre());
    if(nuevoNombre == null) return;
    String nuevoApellido = JOptionPane.showInputDialog("Ingrese el apellido", i.getApellido());
    if(nuevoApellido == null) return;
    String nuevaPass = JOptionPane.showInputDialog("Ingrese la contraseña", i.getContraseña());
    if(nuevaPass == null )return;
    i.setNombre(nuevoNombre);
    i.setApellido(nuevoApellido);
    i.setContraseña(nuevaPass);
    UsuarioControler.guardarUsuarios();
    JOptionPane.showMessageDialog(null, "Datos actualizados");
    
    }//GEN-LAST:event_btnEditarInstructorActionPerformed

    private void btnBuscarInstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarInstructorActionPerformed
     UsuarioControler u = new UsuarioControler();
     String codigo = JOptionPane.showInputDialog("Ingrese código del Instructor");

     if(codigo == null) return;

     Usuario usuario = u.buscarPorCodigo(codigo);


      if(usuario == null){
      JOptionPane.showMessageDialog(null, "Instructor no encontrado");
     return;
  }


if(!(usuario instanceof instructor)){
    JOptionPane.showMessageDialog(null, "El código no pertenece a un instructor");
    return;
}


instructor i = (instructor) usuario;


String info = "Código: " + i.getCodigo() +
              "\nContraseña: " + i.getContraseña() +
              "\nNombre: " + i.getNombre() +
              "\nApellido: " + i.getApellido() +
              "\nFecha Nacimiento: " + i.getFechaNacimiento() +
              "\nGénero: " + i.getGenero();

JOptionPane.showMessageDialog(null, info);
    }//GEN-LAST:event_btnBuscarInstructorActionPerformed

    private void btnEliminarInstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarInstructorActionPerformed
    UsuarioControler u = new UsuarioControler();
     String codigo = JOptionPane.showInputDialog("Ingrese código del instructor");
     if(codigo == null) return;
     Usuario usuario = u.buscarPorCodigo(codigo); 
     if(usuario == null){
      JOptionPane.showMessageDialog(null, "Instructor  no encontrado");
     return;
  }


    if(!(usuario instanceof instructor)){
    JOptionPane.showMessageDialog(null, "El código no pertenece a un Instructor");
    return;
    }
    instructor i = (instructor) usuario; 
     int confirm = JOptionPane.showConfirmDialog(null, "¿Seguro que desea eliminar?");
     if (confirm == JOptionPane.YES_OPTION){
    boolean eliminado = u.eliminarUsuario(codigo);

    if(eliminado){
        JOptionPane.showMessageDialog(null, "Eliminado correctamente");
    }else{
        JOptionPane.showMessageDialog(null, "Error al eliminar");
    }
    }
    }//GEN-LAST:event_btnEliminarInstructorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaGestionInstructores().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarInstructor;
    private javax.swing.JButton btnCargarCSV;
    private javax.swing.JButton btnCrearInstructor;
    private javax.swing.JButton btnEditarInstructor;
    private javax.swing.JButton btnEliminarInstructor;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
