/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto2.view;

import com.mycompany.proyecto2.controller.UsuarioControler;
import com.mycompany.proyecto2.main.abstracto.Usuario;
import com.mycompany.proyecto2.main.utils.Rol;
import com.mycompany.proyecto2.model.estudiante;
import javax.swing.JOptionPane;

/**
 *
 * @author erick
 */
public class VistaGestionEstudiante extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaGestionEstudiante.class.getName());

    /**
     * Creates new form VistaGestionEstudiante
     */
    public VistaGestionEstudiante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistarEstudiante = new javax.swing.JButton();
        btnBuscarEstudiante = new javax.swing.JButton();
        btnEditarEstudiante = new javax.swing.JButton();
        btnEliminarEstudiante = new javax.swing.JButton();
        btnCargarCSV = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRegistarEstudiante.setText("Crear Estudiante");
        btnRegistarEstudiante.addActionListener(this::btnRegistarEstudianteActionPerformed);

        btnBuscarEstudiante.setText("Buscar Estudiante");
        btnBuscarEstudiante.addActionListener(this::btnBuscarEstudianteActionPerformed);

        btnEditarEstudiante.setText("Editar Estudiante");
        btnEditarEstudiante.addActionListener(this::btnEditarEstudianteActionPerformed);

        btnEliminarEstudiante.setText("Eliminar Estudiante");
        btnEliminarEstudiante.addActionListener(this::btnEliminarEstudianteActionPerformed);

        btnCargarCSV.setText("Cargar CSV");
        btnCargarCSV.addActionListener(this::btnCargarCSVActionPerformed);

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Gestion Estudiantes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRegistarEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscarEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(btnEditarEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEliminarEstudiante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCargarCSV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(68, 68, 68))
            .addGroup(layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jLabel1)
                .addContainerGap(235, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistarEstudiante)
                    .addComponent(btnEliminarEstudiante))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarEstudiante)
                    .addComponent(btnCargarCSV))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarEstudiante)
                    .addComponent(btnRegresar))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnBuscarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEstudianteActionPerformed
     UsuarioControler u = new UsuarioControler();
     String codigo = JOptionPane.showInputDialog("Ingrese código del estudiante");

     if(codigo == null) return;

     Usuario usuario = u.buscarPorCodigo(codigo);


      if(usuario == null){
      JOptionPane.showMessageDialog(null, "Estudiante no encontrado");
     return;
  }


if(!(usuario instanceof estudiante)){
    JOptionPane.showMessageDialog(null, "El código no pertenece a un estudiante");
    return;
}


estudiante e = (estudiante) usuario;


String info = "Código: " + e.getCodigo() +
              "\nContraseña: " + e.getContraseña() +
              "\nNombre: " + e.getNombre() +
              "\nApellido: " + e.getApellido() +
              "\nFecha Nacimiento: " + e.getFechaNacimiento() +
              "\nGénero: " + e.getGenero();

JOptionPane.showMessageDialog(null, info);
    }//GEN-LAST:event_btnBuscarEstudianteActionPerformed

    private void btnRegistarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarEstudianteActionPerformed
        VistaRegistrarse vRegistrarse = new VistaRegistrarse();
        vRegistrarse.setVisible(true);
    }//GEN-LAST:event_btnRegistarEstudianteActionPerformed

    private void btnEditarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarEstudianteActionPerformed
      UsuarioControler u = new UsuarioControler();
     String codigo = JOptionPane.showInputDialog("Ingrese código del estudiante");
     if(codigo == null) return;
     Usuario usuario = u.buscarPorCodigo(codigo); 
     if(usuario == null){
      JOptionPane.showMessageDialog(null, "Estudiante no encontrado");
     return;
  }


    if(!(usuario instanceof estudiante)){
    JOptionPane.showMessageDialog(null, "El código no pertenece a un estudiante");
    return;
    }
    estudiante e = (estudiante) usuario;
    String nuevoNombre = JOptionPane.showInputDialog("Nuevo nombre", e.getNombre());
    if(nuevoNombre == null) return;
    String nuevoApellido = JOptionPane.showInputDialog("Nuevo apellido", e.getApellido());
    if(nuevoApellido == null) return;
    String nuevaPass = JOptionPane.showInputDialog("Nueva contraseña", e.getContraseña());
    if(nuevaPass == null) return;
    e.setNombre(nuevoNombre);
    e.setApellido(nuevoApellido);
    e.setContraseña(nuevaPass);
    UsuarioControler.guardarUsuarios();
    JOptionPane.showMessageDialog(null, "Estudiante actualizado");

      
    }//GEN-LAST:event_btnEditarEstudianteActionPerformed

    private void btnEliminarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEstudianteActionPerformed
     UsuarioControler u = new UsuarioControler();
     String codigo = JOptionPane.showInputDialog("Ingrese código del estudiante");
     if(codigo == null) return;
     Usuario usuario = u.buscarPorCodigo(codigo); 
     if(usuario == null){
      JOptionPane.showMessageDialog(null, "Estudiante no encontrado");
     return;
    }
    if(!(usuario instanceof estudiante)){
    JOptionPane.showMessageDialog(null, "El código no pertenece a un estudiante");
    return;
    }
    estudiante e = (estudiante) usuario;
    int confirm = JOptionPane.showConfirmDialog(null, "¿Seguro que desea eliminar?");

    if(confirm == JOptionPane.YES_OPTION){
    boolean eliminado = u.eliminarUsuario(codigo);

    if(eliminado){
        JOptionPane.showMessageDialog(null, "Eliminado correctamente");
    }else{
        JOptionPane.showMessageDialog(null, "Error al eliminar");
    }
    }
    
    }//GEN-LAST:event_btnEliminarEstudianteActionPerformed

    private void btnCargarCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarCSVActionPerformed
        UsuarioControler u = new UsuarioControler();
        u.cargarCSVUsuarios(Rol.ESTUDIANTE);
    }//GEN-LAST:event_btnCargarCSVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaGestionEstudiante().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarEstudiante;
    private javax.swing.JButton btnCargarCSV;
    private javax.swing.JButton btnEditarEstudiante;
    private javax.swing.JButton btnEliminarEstudiante;
    private javax.swing.JButton btnRegistarEstudiante;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
