/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto2.view;

import com.mycompany.proyecto2.controller.CursoControler;
import com.mycompany.proyecto2.main.abstracto.Curso;
import com.mycompany.proyecto2.main.abstracto.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author erick
 */
public class VistaEstudiante extends javax.swing.JFrame {
    private Usuario usuario;
    private CursoControler c;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaEstudiante.class.getName());

    /**
     * Creates new form VistaEstudiante
     */
    public VistaEstudiante(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
        this.c = new CursoControler();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Ver cursos asignados");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Asignarse a un curso");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Ver cursos ");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("Cerrar sesion");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Estudiante");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(73, 73, 73))
            .addGroup(layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      

    Curso[] cursos = c.getCursos();
    int total = c.getContadorCursos();

    String lista = "";

    for(int i = 0; i < total; i++){
        if(cursos[i].estaInscrito(usuario.getCodigo())){
            lista += cursos[i].getCodigo() + " - " + cursos[i].getNombre() + "\n";
        }
    }

    if(lista.equals("")){
        lista = "No estás inscrito en ningún curso";
    }

    JOptionPane.showMessageDialog(null, lista);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     

    String codigo = JOptionPane.showInputDialog("Ingrese código del curso");
    if(codigo == null) return;

    Curso curso = c.buscarCurso(codigo);

    if(curso == null){
        JOptionPane.showMessageDialog(null, "Curso no encontrado");
        return;
    }

    boolean exito = curso.inscribir(usuario.getCodigo());

    if(!exito){
        JOptionPane.showMessageDialog(null, "No hay cupo disponible");
        return;
    }

    CursoControler.guardarCursos();

    JOptionPane.showMessageDialog(null, "Inscripción exitosa");
   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    

    Curso[] cursos = c.getCursos();
    int total = c.getContadorCursos();

    if(total == 0){
        JOptionPane.showMessageDialog(null, "No hay cursos");
        return;
    }

    String lista = "";

    for(int i = 0; i < total; i++){
        lista += cursos[i].getCodigo() + " - " + cursos[i].getNombre() +
                 " (Cupo: " + cursos[i].getInscritos() + "/" + cursos[i].getCupoMax() + ")\n";
    }

    JOptionPane.showMessageDialog(null, lista);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
