/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto2.view;

import com.mycompany.proyecto2.controller.CursoControler;
import com.mycompany.proyecto2.main.abstracto.Curso;
import javax.swing.JOptionPane;

/**
 *
 * @author erick
 */
public class VistaGestionCursos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaGestionCursos.class.getName());

    /**
     * Creates new form GestionCursos
     */
    public VistaGestionCursos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCrearCurso = new javax.swing.JButton();
        btnBuscarCurso = new javax.swing.JButton();
        btnEditarCurso = new javax.swing.JButton();
        btnEliminarCurso = new javax.swing.JButton();
        btnCargarCSV = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCrearCurso.setText("Crear Curso");
        btnCrearCurso.addActionListener(this::btnCrearCursoActionPerformed);

        btnBuscarCurso.setText("Buscar Curso");
        btnBuscarCurso.addActionListener(this::btnBuscarCursoActionPerformed);

        btnEditarCurso.setText("Editar Curso");
        btnEditarCurso.addActionListener(this::btnEditarCursoActionPerformed);

        btnEliminarCurso.setText("Eliminar Curso");
        btnEliminarCurso.addActionListener(this::btnEliminarCursoActionPerformed);

        btnCargarCSV.setText("Cargar CSV");
        btnCargarCSV.addActionListener(this::btnCargarCSVActionPerformed);

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Gestion De Cursos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCrearCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscarCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(btnEditarCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCargarCSV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarCurso, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84))
            .addGroup(layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearCurso)
                    .addComponent(btnEliminarCurso))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarCurso)
                    .addComponent(btnCargarCSV))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarCurso)
                    .addComponent(btnRegresar))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
      this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnCrearCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCursoActionPerformed
    VistaRegistrarCurso vRegistrarC = new VistaRegistrarCurso();
    vRegistrarC.setVisible(true);
    }//GEN-LAST:event_btnCrearCursoActionPerformed

    private void btnBuscarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCursoActionPerformed
      CursoControler c = new CursoControler();

    String codigo = JOptionPane.showInputDialog("Ingrese código del curso");
    if(codigo == null) return;

    Curso curso = c.buscarCurso(codigo);

    if(curso != null){
        JOptionPane.showMessageDialog(null,
            "Código: " + curso.getCodigo() +
            "\nNombre: " + curso.getNombre() +
            "\nDescripción: " + curso.getDescripcion() +
            "\nCupo: " + curso.getCupoMax() +
            "\nInscritos: " + curso.getInscritos()
        );
    } else {
        JOptionPane.showMessageDialog(null, "Curso no encontrado");
    }
    }//GEN-LAST:event_btnBuscarCursoActionPerformed

    private void btnEditarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCursoActionPerformed
     CursoControler c = new CursoControler();
    String codigo = JOptionPane.showInputDialog("Ingrese código del curso");
    if(codigo == null) return;

    Curso curso = c.buscarCurso(codigo);

    if(curso == null){
        JOptionPane.showMessageDialog(null, "Curso no encontrado");
        return;
    }

    String nombre = JOptionPane.showInputDialog("Nuevo nombre", curso.getNombre());
    if(nombre == null) return;

    String descripcion = JOptionPane.showInputDialog("Nueva descripción", curso.getDescripcion());
    if(descripcion == null) return;

    int cupo;
    try{
        cupo = Integer.parseInt(JOptionPane.showInputDialog("Nuevo cupo", curso.getCupoMax()));
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Cupo inválido");
        return;
    }

    c.editarCurso(codigo, nombre, descripcion, cupo);

    JOptionPane.showMessageDialog(null, "Curso actualizado");
    }//GEN-LAST:event_btnEditarCursoActionPerformed

    private void btnEliminarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCursoActionPerformed
    CursoControler c = new CursoControler();

    String codigo = JOptionPane.showInputDialog("Ingrese código del curso a eliminar");
    if(codigo == null) return;

    boolean eliminado = c.eliminarCurso(codigo);

    if(eliminado){
        JOptionPane.showMessageDialog(null, "Curso eliminado correctamente");
    } else {
        JOptionPane.showMessageDialog(null, "Curso no encontrado");
    }
    }//GEN-LAST:event_btnEliminarCursoActionPerformed

    private void btnCargarCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarCSVActionPerformed
     CursoControler c = new CursoControler();
     c.cargarCSV();
    

    }//GEN-LAST:event_btnCargarCSVActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new VistaGestionCursos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCurso;
    private javax.swing.JButton btnCargarCSV;
    private javax.swing.JButton btnCrearCurso;
    private javax.swing.JButton btnEditarCurso;
    private javax.swing.JButton btnEliminarCurso;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
